# Generated by Django 4.1.2 on 2023-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='joke',
        ),
        migrations.AddField(
            model_name='joke',
            name='bottom_text',
            field=models.CharField(default='bruh', max_length=1024),
        ),
        migrations.AddField(
            model_name='joke',
            name='top_text',
            field=models.CharField(default='bruh', max_length=1024),
        ),
    ]
