# Generated by Django 4.1.2 on 2023-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_joke_joke_joke_bottom_text_joke_top_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='bottom_text',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='joke',
            name='top_text',
            field=models.CharField(max_length=1024),
        ),
    ]
